version: "3.8"
services:
  mongo:
    image: geppettotest/mongo-local:april2020
    container_name: mongo-4630
    restart: unless-stopped
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password
    volumes:
      - inputtest_4630-volume:/data/db
    ports:
      - "27018:27017"
    healthcheck:
      test: echo 'db.runCommand({serverStatus:1}).ok' | mongo admin -u root -p root --quiet | grep 1
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 40s

  camunda:
    image: geppettotest/camunda-local:april2020
    container_name: camunda-4630
    ports:
      - "0000:8080"

  authproxy:
    build: ../../../application/services/default_services/authproxy
    image: authproxy
    container_name: authproxy-4630
    ports:
      - "0000:8001"
    env_file: .env
    depends_on:
      - mongo
      - camunda

  camundaservice:
    build: ../../../application/services/default_services/camunda
    image: camundaservice
    container_name: camundasvc-4630
    ports:
      - "0000:8002"
    env_file: .env
    depends_on:
      - mongo
      - camunda

  securitymanager:
    build: ../../../application/services/default_services/securitymanager
    image: securitymanager
    container_name: securitymanager-4630
    ports:
      - "0000:8003"
    env_file: .env
    depends_on:
      - mongo
      - camunda

  apigateway:
    build: ../../../application/services/custom_services/apigateway
    image: apigateway
    container_name: apigateway-4630
    ports:
      - "8000:8000"
    env_file: .env
    depends_on:
      - camunda
      - camundaservice
      - authproxy
      - securitymanager
      - inputtesting



  inputtesting: 
    build: ../../../application/services/custom_services/inputtesting
    image: inputtesting-4630
    container_name: inputtesting-4630
    ports: 
      - 8006:8006
    env_file: .env
    depends_on:
      - mongo


volumes:
  inputtest_4630-volume:
    driver: local
